### ISSUE TITLE
BUG: Large memory usage when caching a large number of tables causing crashing

### ISSUE THREAD

**Issue by avimallu** [beekeeper-studio/beekeeper-studio#479] opened 2020-12-15 11:30 UTC
**Description**
I have a Redshift based DB that has upwards of 18,000 tables (yes, 18K). When I open a connection to it, Beekeeper tries to load the entire tableset to memory, taking up well over 2.5GB of RAM on my system (8GB RAM total). While having auto-complete functionality is invaluable, having a client that doesn't crash after running a few queries is even more important.

**To Reproduce**
1. Open a Redshift connecting that has several hundred tables.
2. Watch RAM fill up in task manager, along with high CPU usage.

**Expected behavior**
Ideally, to avoid hogging up such a large amount of memory and keeping in line with Beekeeper's easy-to-use principle, I would expect some sort of local caching that can either get automatically updated in the background after a first time setup, and then get updated on the fly with no user interaction.

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version 1.8.11, portable version.

**Additional context**
Not an issue for other databases on the same server that have fewer tables.

**Comment by rathboma** [comment] 2020-12-22 15:26
Yes, currently it loads all tables AND all table columns into memory. It certainly should not use that amount of RAM, so that's something I can look into, but it does this currently so it can provide auto-complete information in the code editor for both tables and columns.

Certainly you are an outlier here (18k, good stuff), but I definitely want this use case to be covered.

Sorry you've hit memory issues :-(

**Comment by rathboma** [comment] 2020-12-22 15:38
Notes for implementation:
- Try using https://github.com/tangbc/vue-virtual-scroll-list for large list rendering
- Try using Object.freeze in the state when adding tables

**Comment by avimallu** [comment] 2020-12-22 16:00
I appreciate the direction Beekeeper is taking - so will be happy to test should you have potential fixes down the line if the situation remains the same.

To give you context on why my case is not necessarily an outlier - this is in a large commercial organization with a massive set of data, where users have the ability to create tables themselves for any ad-hoc purpose. This is likely to become a more common situation when Beekeeper becomes a little more mainstream.

**Comment by rathboma** [comment] 2023-10-25 19:48
Duplicate of #748

**Closed** 2023-11-10 18:32 UTC
Labels: bug, accepted :+1:

**Comment by dlt-** [comment] 2024-09-08 08:19
Still crashes with 90k tables, in both Mac (arm) and Windows builds (v 4.6.4).  It shows first tables and I may be able to scroll down the list for several hundred tables, until it stops working.

CPU usage stays at 100% (one core), memory usage at about 700M. The user interface becomes totally unresponsive and only way to quit is to terminate the process.
