### ISSUE TITLE
BUG: Wrong/repeated results in group by functions on columns

### ISSUE THREAD

**Issue by LLTTDAY** [beekeeper-studio/beekeeper-studio#340] opened 2020-09-19 17:19 UTC
I have a table of rows that I am trying to group by two columns, while summing the other two columns. These columns are different in almost every row. When I run the query, I get the same results for each summed column. See screenshot from a different client showing the correct results.

1. Run the group by query below

**Expected behavior**
I would expect different results for the two summed columns but they are the same.

**Screenshots / Gifs**
<img width="906" alt="Incorrect results" src="https://user-images.githubusercontent.com/4205702/93677005-7af6fc80-fa61-11ea-9360-01cfafb6011a.png">

<img width="778" alt="Correct results" src="https://user-images.githubusercontent.com/4205702/93677272-8fd39000-fa61-11ea-9439-148f40a7d5fe.png">

**Version Information (please complete the following information):**
 - OS: MacOS Catalina
 - App Version: 1.7.5

**Comment by UtechtDustin** [comment] 2020-09-19 17:22
Duplicate of #326 and #176

**Comment by rathboma** [comment] 2020-09-20 00:40
Yep! I've put this bug on the next milestone to fix. It's a limitation of the db libraries. There's a workaround though.

**Comment by rathboma** [comment] 2020-09-20 00:40
Closing in favor of the dupes. I'll get it fixed though!

**Closed** 2020-09-20 00:40 UTC
