### ISSUE TITLE
Rpm package?

### ISSUE THREAD

**Issue by sundowndev** [beekeeper-studio/beekeeper-studio#2402] opened 2024-09-04 06:48 UTC
As a Fedora user, I'd like to have a rpm package just like the .deb already distributed. Thanks!

**Comment by rathboma** [comment] 2024-09-10 22:15
Hey! We're going to be consolidating the two apps soon, so this will happen.

Duplicate of #202

**Closed by rathboma** 2024-09-10 22:15 UTC
