### ISSUE TITLE
FEAT: Provide the ability to collapse left side view

### ISSUE THREAD

**Issue by Cfun1** [beekeeper-studio/beekeeper-studio#488] opened 2020-12-23 08:58 UTC
Currently you can reduce the width of the left side view but it seems it is restricted by a minimum width which is not enough in some cases, especially that you still have space to reduce but you cannot. Providing the ability to collapse it will be helpful if you want to focus on your table data view by giving more space to display columns.

**Comment by rathboma** [comment] 2020-12-23 22:47
Yep! Duplicate of #458

**Closed by rathboma** 2020-12-23 22:47 UTC
