### ISSUE TITLE
BUG: Fonts missing on Fedora 32, Arch, and Manjaro when using the snap version of Beekeeper Studio

### ISSUE THREAD

**Issue by MiguelOrdnz** [beekeeper-studio/beekeeper-studio#314] opened 2020-09-01 19:16 UTC
**Description:**
All the characters are unrecognizable on the dialog windows, a good example is when you choose the SQLite file, please take a look at the logs at the last line where the dialog window is launched:

`Gtk-Message: 13:00:37.786: GtkDialog mapped without a transient parent. This is discouraged.`
 
**To Reproduce:**
1. Select connection type SQLite3
2. Click on choose file

**Screenshot:**
![image](https://user-images.githubusercontent.com/9314209/91895269-32170980-ec54-11ea-848a-e9ddd286436c.png)

**Log:**
```
➜  ~ beekeeper-studio
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Gtk-Message: 13:00:25.134: Failed to load module "pk-gtk-module"
Gtk-Message: 13:00:25.138: Failed to load module "pk-gtk-module"
13:00:25.875 › initializing background
13:00:25.883 › initializing user ORM connection
13:00:25.884 › registering schema
13:00:25.944 › Creating first window
13:00:26.163 › running migrations
running migrations
13:00:26.177 › getting settings
13:00:26.190 › setting up the menu
MENUTEMPLATE [
  {
    label: 'File',
    submenu: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  {
    label: 'Edit',
    submenu: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  {
    label: 'View',
    submenu: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  },
  { label: 'Help', submenu: [ [Object], [Object], [Object] ] }
]
13:00:26.199 › Building the window
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:62262) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:62262) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
13:00:26.262 › managing updates
(node:62366) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.beekeeper-studio/.org.chromium.Chromium.bSwvtn'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:62366) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.beekeeper-studio/.org.chromium.Chromium.bSwvtn'. This is deprecated, see https://github.com/electron/electron/issues/18397.
Gtk-Message: 13:00:37.786: GtkDialog mapped without a transient parent. This is discouraged.
```

**Version Information:**
 - OS: Fedora 32 (Workstation Edition) x86_64 GNOME Shell 3.36.4

```
          /:-------------:\          xxxxx@xxxxxxxx
       :-------------------::        --------------------------- 
     :-----------/shhOHbmp---:\      OS: Fedora 32 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:     Host: xxxxxxx
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.7.14-200.fc32.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 3 hours, 14 mins 
,------------:MMMd--------    ---:   Packages: 2025 (rpm), 6 (snap) 
:------------:MMMd-------    .---:   Shell: zsh 5.8 
:----    oNMMMMMMMMMNho     .----:   Resolution: xxxxxxx
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 
:-    -------:MMMd--------------:    WM: Mutter 
:-   --------/MMMd-------------;     WM Theme: Adwaita 
:-    ------/hMMMy------------:      Theme: Adwaita-dark [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Icons: Adwaita [GTK2/3] 
:---:sdNMMMMNds:------------:        Terminal: tilix 
:------:://:-------------::          CPU: Intel i5 M 520 (4) @ 2.400GHz 
:---------------------://            GPU: Intel Core Processor 
                                     Memory: 3787MiB / 5734MiB 
```

**Comment by rathboma** [comment] 2020-09-02 20:50
I've seen this before. Duplicate of #32.

I'm not sure what the cause is. I've spun up Fedora and it works fine. That's supposed to be a native GTK file picker.

Do you have any custom fonts or anything?

**Comment by rathboma** [comment] 2020-09-02 21:28
Ok, I've narrowed this down to `snap` versions. If you download the AppImage it will work right.

I'll try to figure out how to fix it. Thanks for the bug report!

**Comment by rathboma** [comment] 2020-09-02 21:55
This is the bug - https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/59

Seems like a change in a newer version of a font configuration library that's messing with the Snap sandbox.

There are workarounds listed in that forum, but none of them seem to work for me. I'll be publishing an RPM soon, so hopefully that'll be more reliable than the snap version.

Matthew

**Comment by rathboma** [comment] 2021-02-25 03:03
Can you try this potential workaround:


```
$ sudo rm -f /var/cache/fontconfig/*
$ rm -f ~/.cache/fontconfig
```
From: https://forum.snapcraft.io/t/snap-store-fonts-on-arch-linux-are-merely-empty-rectangles/15373/9

**Comment by rathboma** [comment] 2021-02-25 03:04
I'm closing this as there is nothing I can do about it -- it is a Snapd issue

**Closed by rathboma** 2021-02-25 03:04 UTC
Labels: accepted :+1:, blocked :stop_sign:, bug
