### ISSUE TITLE
v1.3.0 doesn't allows copy paste.

### ISSUE THREAD

**Issue by codeoholic** [beekeeper-studio/beekeeper-studio#116] opened 2020-05-14 12:19 UTC
Post 1.3.0 update from 1.2, I am unable to copy/paste text from/to the application.

Running v1.3.0 of beekeeper on macOS 10.15.4.

**Comment by rathboma** [comment] 2020-05-14 21:59
Huh. I've never heard of that. Nothing to do with Mac packaging was changed that I know of. Let me test on my macbook and I'll let you know what I find.

**Comment by jonorossi** [comment] 2020-05-15 04:15
I too can confirm I cannot copy anything in/out on macOS. First time using Beekeeper Studio though.

**Comment by rathboma** [comment] 2020-05-15 12:39
bah, I know exactly what is wrong. Fixing today

**Comment by rathboma** [comment] 2020-05-15 12:57
@codeoholic @jonorossi can you download the mac build from here https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/105684335

and check:
1. If the issue is fixed
2. That you can still close tabs with cmd+w

**Comment by rathboma** [comment] 2020-05-15 12:58
Once you verify it, I'll merge, close the issue, and do a point release today

**Comment by jonorossi** [comment] 2020-05-15 13:53
> and check:
> 
> 1. If the issue is fixed
> 2. That you can still close tabs with cmd+w

1. yes
2. yes

**Comment by snoozan** [comment] 2020-05-15 13:59
Hi! Also confirmed your fix works. I can copy paste :)

**Closed** 2020-05-15 14:11 UTC
Labels: bug, mac

**Comment by rathboma** [comment] 2020-05-15 14:14
build 1.3.1 being pushed out now to fix this for everyone
