### ISSUE TITLE
BUG: PostgreSQL search result is different from psql and Table Plus

### ISSUE THREAD

**Issue by arvi** [beekeeper-studio/beekeeper-studio#396] opened 2020-10-17 10:05 UTC
**Describe the bug**
Currently following a beginner's PostgreSQL tutorial with Beekeeper as my SQL editor and it didn't display the same result as the instructor is showing. I tried using psql (what the instructor is showing) and also tried TablePlus. Both are displaying same result.

Check the last two columns (left TablePlus, right BeeKeeper Studio):
https://ibb.co/ZfSym4v

**To Reproduce**
1. Create a PostgreSQL connection
2. Create car data or you can use mine: https://gist.github.com/arvi/5b144af0412281170259d0e1bf1715d8
3. Run the query
SELECT id, make, price, 
ROUND(price * .10,2), 
ROUND(price - (price * .10),2) FROM car;
4. Compare with psql, TablePlus (free trial)

**Expected behavior**
It should be same as psql or other SQL editor query result

**Screenshots / Gifs**
https://ibb.co/ZfSym4v

**Version Information (please complete the following information):**
 - OS: Mac Catalina
 - App Version: Version 1.7.5 (1.7.5)

**Additional context**
Thank You.

**Comment by MasterOdin** [comment] 2020-10-17 15:38
Duplicate of #176 and #326. The problem here is that beekeeper does not handle having the same name for multiple columns.

**Comment by rathboma** [comment] 2020-10-18 02:18
@arvi yes so sorry you've hit this bug. We're preparing a small release now and then the next version will fix this problem.

Here's how to work around this with your sql:

```sql
SELECT id, make, price,
ROUND(price * .10,2) as price1,
ROUND(price - (price * .10),2) as price2 FROM car;

```

**Closed** 2020-10-18 02:19 UTC
