### ISSUE TITLE
FEAT: Export and import entire database

### ISSUE THREAD

**Issue by runtimeinteractive** [beekeeper-studio/beekeeper-studio#1201] opened 2022-04-28 10:12 UTC
**Is your feature request related to a problem? Please describe.**
Yes. Sometimes I need to clone one entire database to another and I cannot do it using this client. HeidiSQL is the client I need to use to achieve this functionality.

**Describe the solution you'd like**
Allow exporting of an entire database instead of a single table as it is now. I think an quick fix for this is to allow selecting of multiple tables and exporting them individually behind the scenes.

**Describe alternatives you've considered**
There are no alternatives which I could find for this client. My alternative is to use HeidiSQL which is junk for everything else.

**Additional context**
Nothing else.

**Database type, if appropriate**
All available databases.

**Comment by jpSimkins** [comment] 2022-05-08 19:26
For me, this is not going to replace MySQL Workbench until I have the ability to export and import. Seems like a core responsibility of a client like this. Other than that, this is a great product! User management would also be a nice feature eventually too

**Comment by AdsonCicilioti** [comment] 2022-05-20 20:39
I was surprised that I didn't already find this functionality. I was going to open this issue, but I searched and saw this already existing.
I endorse the request. It will really make the app even better.

**Comment by Zerotask** [comment] 2022-06-04 13:10
https://github.com/beekeeper-studio/beekeeper-studio/issues/778 is already accepted

**Comment by runtimeinteractive** [comment] 2022-06-05 23:18
> https://github.com/beekeeper-studio/beekeeper-studio/issues/778 is already accepted

Sorry, I didn't look back that far. Thanks

**Comment by Zerotask** [comment] 2022-06-05 23:26
You can simply use the search ;)

**Comment by jpSimkins** [comment] 2022-06-06 13:48
@Zerotask I did search but I was searching for import not export. Perhaps update your title to include import/export as this is why I +1 this post. The way that post reads, it is only asking for export which is not what this one is asking for.

**Comment by xiangzhaozhao** [comment] 2022-06-12 15:56
It is strongly recommended to add export multiple tables,thanks.

**Comment by xiangzhaozhao** [comment] 2022-06-12 15:57
> It is strongly recommended to add export multiple tables,thanks.

If not this function,i will give up  this app.

**Comment by rathboma** [comment] 2022-06-20 18:49
Hey everyone! Yes man the app really needs full export/import I totally agree. It'll come in time :-).

Going to close this as a duplicate of #778, but know that I do care about this issue!

Matthew

**Closed by rathboma** 2022-06-20 18:49 UTC

**Comment by anilsg** [comment] 2022-07-29 01:26
> > It is strongly recommended to add export multiple tables,thanks.

> If not this function,i will give up this app.

:wave:
