### ISSUE TITLE
BUG: high port number does not get saved

### ISSUE THREAD

**Issue by pixelpeter** [beekeeper-studio/beekeeper-studio#1200] opened 2022-04-28 07:04 UTC
Entering a high port number like `33236` for a Postgres connection it will always be reset to `5432`.
Only way to make the connection work (although not saved) is to type {enter} after entering the port number

Beekeeper Studio 3.4.1
MacOS Monterey 12.3.1

**Comment by UtechtDustin** [comment] 2022-05-06 21:17
Duplicate of #1203

**Comment by rathboma** [comment] 2022-05-20 14:54
fixed in master, release coming today

**Closed by rathboma** 2022-05-20 14:54 UTC
