### ISSUE TITLE
FEAT: Support for No SQL Database.

### ISSUE THREAD

**Issue by BroJenuel** [beekeeper-studio/beekeeper-studio#612] opened 2021-03-26 15:45 UTC
**Is your feature request related to a problem? Please describe.**
Some or more companies today are starting to use mongodb, and I also work on those companies.. I was inloved by the design of the beekeeper studio, its really fun using it., I don't want to use different software to manage database, I want to use beekeeper to manage all databases.

**Describe the solution you'd like**
The solution I like is to have a support for No Sql databases.

**Describe alternatives you've considered**
A lot of developers today are looking for tools, specially like this tool to manage databases, if this software can support different databases, I think this software will become big.

**Comment by rathboma** [comment] 2021-03-29 21:57
Hey! Yes, I'd :heart: to support NoSQL databases, MongoDB in particular.

Unfortunately at the moment we just lack the resources to add this feature, it's more work than a 'normal' database:

- Figure out a way to support our database API for non-sql datastores (not easy)
- Add a new display mode that can handle deeply nested objects
- MongoDB query support for the editor (code completion, theme, etc)

So really it does require a lot of work!

duplicate of #258.

@BroJenuel I'm going to close this issue for now, not because I don't care, and we will get this done, but probably not for at least a year.

Anyone else finding this issue: We will 100% integrate this if someone submits a PR, even if UX work isn't perfect!

**Closed by rathboma** 2021-03-29 21:57 UTC

**Comment by BroJenuel** [comment] 2021-03-30 04:34
Looking forward to it :) <3

**Comment by barrrettt** [comment] 2022-03-29 08:40
Why not Redis too?  :grinning:
