### ISSUE TITLE
BUG: JSON content incorrectly identified as query parameter

### ISSUE THREAD

**Issue by sfyfedotcom** [beekeeper-studio/beekeeper-studio#809] opened 2021-09-21 08:33 UTC
**Describe the bug:**

When executing a query with a JSON string, an integer value is incorrectly identified as a query parameter

**To Reproduce:**

Run query like:
```
insert into `notifications` (`context_dump`, `created_at`, `id`, `is_read`, `organization_id`, `project_id`, `sent_to`, `type`, `updated_at`, `user_id`)
values ('{\"value\":1234}', '2021-08-13 08:39:10', 1, 1, 1, NULL, 'john@doe.com', 'NotificationType', '2021-09-01 14:16:55', 1)
```

A "Provide parameter values" modal appears asking to enter the parameter value for `:1234`, but it is not a query parameter.

![Screenshot 2021-09-21 at 09 31 50](https://user-images.githubusercontent.com/10885475/134138605-42a7c33e-1008-4e9f-83bb-4a64fae1f769.png)

**Version Information:**

OS: macOS 11.5.2
App Version: 2.1.3

**Comment by rathboma** [comment] 2021-09-27 16:24
It will be fixed soon! Yes this is due to our terrible params parser. I just recently upgraded an underlying library that allows proper parameter extraction.

**Comment by rathboma** [comment] 2021-09-27 16:24
duplicate of #713

**Closed by rathboma** 2021-09-27 16:24 UTC
