### ISSUE TITLE
BUG: Columns with same name aren't correct displayed

### ISSUE THREAD

**Issue by LeoFalco** [beekeeper-studio/beekeeper-studio#547] opened 2021-02-08 16:29 UTC
**Describe the bug**
Query result is not correct displayed when query has columns with same names

**To Reproduce**
1. Connect to a database
2. Execute a query like
```sql
select 
  locations.id,
  locations.name,
  floors.id,
  floors.name
from locations
  join floors on floors.location_id  = locations.id
order by
locations.name,
floors.name;
```
3. The result is
![image](https://user-images.githubusercontent.com/25820906/107248579-30c2e780-6a11-11eb-8dfd-fc2ff263222c.png)

**Expected behavior**
Show results correctly, The `locations.id` the first column in screeen shot and `locations.name` the second columns in screeen shot are incorrectly displayed, the values ​​of floors.id and floors.name
were shown in place

**Screenshots / Gifs**
If i run a query using alias to avoid collision of names like:

```sql
select 
locations.id as location_id,
locations.name as location_name,
floors.id as floors_id,
floors.name as floors_name
from locations
  join floors on floors.location_id  = locations.id
order by
locations.name,
floors.name
;
```
the result is correctly displayed
![image](https://user-images.githubusercontent.com/25820906/107248858-813a4500-6a11-11eb-9824-f1d060a45342.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version: 1.9.1

**Comment by UtechtDustin** [comment] 2021-02-08 17:36
Thank you for the report, this bug is a duplicate of #176.

**Comment by rathboma** [comment] 2021-02-08 18:51
@LeoFalco what database are you using? (eg mysql, sqlite, etc, etc)

**Comment by rathboma** [comment] 2021-02-08 18:52
Going to close this, just as we already track it

**Closed by rathboma** 2021-02-08 18:52 UTC
