### ISSUE TITLE
FEAT: vertical edit form

### ISSUE THREAD

**Issue by RiccardoCohen** [beekeeper-studio/beekeeper-studio#1127] opened 2022-03-31 07:35 UTC
**Is your feature request related to a problem? Please describe.**
With many columns, editing cells in the last columns is difficult because we don't see the first (id/name)

**Describe the solution you'd like**
Right click => open edit form => with all fields vertically, and Text fields with a "textarea" with scrollbar

**Describe alternatives you've considered**

**Additional context**

**Database type, if appropriate**

** thanks for your great software **

**Comment by rathboma** [comment] 2022-04-01 15:08
Yeah this is going to come soon :-). Duplicate of #808

**Comment by rathboma** [comment] 2022-04-01 15:08
Closing because I'm tracking it already, but I do care about this feature, and it will come soon.

**Closed by rathboma** 2022-04-01 15:08 UTC
