### ISSUE TITLE
BUG: Lots of partitions and materialized views break the tables list

### ISSUE THREAD

**Issue by pzduniak** [beekeeper-studio/beekeeper-studio#791] opened 2021-09-06 19:22 UTC
**Describe the bug**
Cool software, sucks that I can't use it with one of my databases :(

![image](https://user-images.githubusercontent.com/917230/132255368-a24e60a0-6bde-4a92-9a10-6720430bcf65.png)

I wanted to check how Beekeeper Studio handles Postgres partitions and the result was... this. Only selecting "tables" did not solve the issue.

**To Reproduce**
1. Have a PostgreSQL database that appears to have thousands of partitions and multiple thousands of views that are cleared daily.
1. Connect to that database
1. Watch it break.

**Expected behavior**
It should let me filter by tables and list the ~30 tables in my database. Partitions should probably be hidden.

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]: Windows 10
 - App Version [e.g. help -> About Beekeeper Studio]: 2.0.0

**Comment by rathboma** [comment] 2021-09-14 19:39
Yes :-( Sorry about this. We'll get this fixed soon.

Duplicate of #788.

Closing in favor of the other ticket I am tracking.

**Closed by rathboma** 2021-09-14 19:39 UTC
