### ISSUE TITLE
BUG: Database explorer showing "no entities in database". Entities are not populating by default on launch

### ISSUE THREAD

**Issue by bhanusumanth** [beekeeper-studio/beekeeper-studio#2088] opened 2024-04-05 18:58 UTC
**Describe the bug**
This issue is seen after updating my version to 4.2.8. The tables are populated in database explorer by default. Its not showing tables in explorer everytime I launch and open connection. It says **there are no entities in the my database**. But, the queries are running. Tried relaunching the app, I still get same. explorer is populating with DB entities when I click on refresh entities button.

**To Reproduce**
1. launch the App
2. new Connection
3. No tables shown in database explorer home page

**Expected behavior**
After opening a new connection, by default explorer used to display all entities without doing an action on my end. Now, I have to refresh entities to see the data.

**Screenshots / Gifs**
<img width="769" alt="Screenshot 2024-04-05 at 11 14 19 AM" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/24877676/a93b9ee9-06ab-42d1-974b-de6a908ce743">

**Version Information (please complete the following information):**
 - OS: Mac 14.1.1 
 - App Version 4.2.8
 - Database type and version : MySQL, 5.7.12

**Additional context**

**Comment by not-night-but** [comment] 2024-04-05 19:13
Hey! This is a bug that was introduced yesterday. It's fixed now and should be out in the next release.

I'm gonna close this as it's a duplicate of #2084, thanks for the report though!

**Closed by not-night-but** 2024-04-05 19:13 UTC
