### ISSUE TITLE
FEAT: Insert row on table view

### ISSUE THREAD

**Issue by ggalvez92** [beekeeper-studio/beekeeper-studio#346] opened 2020-09-24 13:54 UTC
I know that insert sql works but I want the visual way, so I wonder if someone can help me with this.

**Comment by UtechtDustin** [comment] 2020-09-25 11:58
Its currently not possible to insert a new row with the ui, we have to implement this first!

**Comment by rathboma** [comment] 2020-09-25 14:21
Yeah, sorry we don't have a GUI way to do this yet :-(. Shouldn't be too hard to implement with tabulator, but requires some time

**Comment by lothas** [comment] 2020-12-14 06:20
Any update on this? It would make the difference between me using Beekeeper Studio or sticking with pgAdmin :)

**Comment by fabscav** [comment] 2021-01-28 21:09
I've created a PR that might come close to what you're requesting: #525

**Comment by MatteoAvalle** [comment] 2021-04-08 10:26
Hi, I'm sorry, I got here asking myself the same question about an interface for inserting and duplicating lines. From the releases page, the PR #525  seems to be merged into release 1.10.2, but I don't see the new menu in this version. Is there an issue about it?

**Comment by thetaPC** [comment] 2021-06-08 20:49
> "Add row" can be found in the dropdown menu in the bottom.
> 
> <img alt="Screen Shot 2021-06-08 at 9 32 16 pm" width="510" src="https://user-images.githubusercontent.com/1054703/121177826-35a18600-c8a1-11eb-8bee-4e6457dfff57.png">

I can confirm that this is visible and working on version 1.12.0.

**Closed** 2022-01-26 02:56 UTC
Labels: enhancement, accepted :+1:
