### ISSUE TITLE
BUG: File open dialog unable to render text

### ISSUE THREAD

**Issue by andrewbrey** [beekeeper-studio/beekeeper-studio#695] opened 2021-06-15 19:13 UTC
**Describe the bug**
When attempting to open a `sqlite` database, the native file open dialog presented when clicking on `Choose File` from the connection selection screen is unable to render the text within the dialog. This includes all buttons/controls as well as file and folder names.

**To Reproduce**
1. Go to the Connection Selection screen
2. Click on `Choose File`
3. Observe text rendered as if the font information is missing

**Expected behavior**
Text should render and be readable :+1: 

**Screenshots / Gifs**

Here is a demonstration of the observed behavior:
![issue_demonstration](https://user-images.githubusercontent.com/34140052/122109145-e348f380-cdd1-11eb-827d-3d5634770180.gif)

**Version Information**

_Snap Installation Info_
![image](https://user-images.githubusercontent.com/34140052/122108717-6289f780-cdd1-11eb-8d90-63c765bae728.png)

_Neofetch Output_
![machine_info](https://user-images.githubusercontent.com/34140052/122108559-31112c00-cdd1-11eb-978a-e3ba21782873.png)

**Additional context**

Note that, as indicated above, I have installed the application via the `Snap` store. I have encountered this issue before and removing then re-installing the application (again, via snap) did fix it but it seems to have regressed.

Perhaps related or helpful, another open source electron app that I've used in the past currently has an open issue reporting the same behavior: https://github.com/Figma-Linux/figma-linux/issues/218.

Also, there is a quite old electron issue about the topic with several related issues linked: https://github.com/electron/electron/issues/9616

**Comment by rathboma** [comment] 2021-06-15 19:15
Hey! This is a bug with the font config for the snap version. Can you try the app image?

This is fixable, but it another frustrating snap problem that's hard to replicate and track down.

Duplicate of #598

**Closed by rathboma** 2021-06-15 19:15 UTC

**Comment by andrewbrey** [comment] 2021-06-15 19:23
I apologize for the duplicate, I didn't find that when I searched a few different terms! By the way, I did a bit more link-following through the related issues and found a (probably ephemeral) fix for the snap package which I'll drop here for posterity - clear and rebuild the font cache:

```bash
rm -rf ~/.cache/fontconfig/*
fc-cache -r
```

After performing the removal and rebuild of my system font cache, the dialog now displays correctly. I'll probably switch over to using the `AppImage` instead of the `Snap` just to avoid this happening again. Cheers!

**Comment by josegus** [comment] 2021-11-05 19:03
> I apologize for the duplicate, I didn't find that when I searched a few different terms! By the way, I did a bit more link-following through the related issues and found a (probably ephemeral) fix for the snap package which I'll drop here for posterity - clear and rebuild the font cache:
> 
> ```shell
> rm -rf ~/.cache/fontconfig/*
> fc-cache -r
> ```
> 
> After performing the removal and rebuild of my system font cache, the dialog now displays correctly. I'll probably switch over to using the `AppImage` instead of the `Snap` just to avoid this happening again. Cheers!

I'm having the same issue. How can I rebuild my system font cache?

**Comment by andrewbrey** [comment] 2021-11-05 19:13
@josegus the quoted code in your message does exactly that - `rm -rf ~/.cache/fontconfig/*` removes all existing font config cache files, then `fc-cache -r` rebuilds the cache files using the currently available fonts. You will likely need to restart `beekeeper` for the changes to take effect.

**Comment by josegus** [comment] 2021-11-05 20:28
> @josegus the quoted code in your message does exactly that - `rm -rf ~/.cache/fontconfig/*` removes all existing font config cache files, then `fc-cache -r` rebuilds the cache files using the currently available fonts. You will likely need to restart `beekeeper` for the changes to take effect.

I did it, the problem continues
![image](https://user-images.githubusercontent.com/13947849/140574470-916768d1-029b-45a7-9622-aab4d74ab19f.png)
