### ISSUE TITLE
FEAT: completion for scheme . table

### ISSUE THREAD

**Issue by DevKleber** [beekeeper-studio/beekeeper-studio#507] opened 2021-01-05 20:48 UTC
Add auto completion, for scheme . table
now is table.column

Using postgres.

**Comment by rathboma** [comment] 2021-01-18 21:50
Yes agreed, we don't have good schema autocompletion right now.

duplicate of #216 

Going to close this issue because I'm already tracking it -- I still care very much about this problem!

**Closed by rathboma** 2021-01-18 21:50 UTC
