### ISSUE TITLE
FEAT: Editable Hotkeys

### ISSUE THREAD

**Issue by bharrison-od** [beekeeper-studio/beekeeper-studio#830] opened 2021-10-04 12:29 UTC
**Is your feature request related to a problem? Please describe.**
I think "Problem" is too strong a word, but coming from Visual Studio / SSMS, I am very used to hitting F5 to run a query. I really like Beekeeper so far, but I often hit F5 and then wonder if beekeeper froze before realizing it's a different hotkey.

**Describe the solution you'd like**
I would like the ability to remap/edit hotkeys so I can assign actions to keys that I'm used to.

**Describe alternatives you've considered**
None. The alternative would be to continue using the assigned keys and eventually I'll get used to those, which for the record, is not a bad solution, just not my preferred one.

**Additional context**
None that I can think of. If there is any other information that would be helpful please let me know!

Thank you so much for this product and for taking the time to review my request!

PS: I'm a software developer, so I cloned the code and poked around a bit, but I can't tell where the hotkeys are assigned/invoked, figuring maybe I could re-assign them and just run Beekeeper locally with different hotkeys if this feature was difficult to implement. Could you maybe also direct me to that location? Thank you!

**Comment by rathboma** [comment] 2021-10-07 21:03
Duplicate of #485

**Closed by rathboma** 2021-10-07 21:03 UTC
