### ISSUE TITLE
FEAT: Export multiple tables (multiple formats - CSV, JSON, SQL, etc) - this is different from 'backup' which is more opinionated.

### ISSUE THREAD

**Issue by virtualLast** [beekeeper-studio/beekeeper-studio#1368] opened 2022-09-07 13:08 UTC
**Details:**
I cannot see how to export an entire database - Im using the linux version.

**Comment by afiaudofia** [comment] 2022-09-16 05:05
Same here. I couldn’t find an export database option.

**Comment by Zerotask** [comment] 2022-09-21 10:56
Duplicate of #778

**Comment by vardumper** [comment] 2023-01-29 14:32
same here.

**Comment by rathboma** [comment] 2023-02-17 18:48
Hey! This isn't supported yet. Coming soon though.

@afiaudofia question -- what format would you want the whole-db export to be in?
@vardumper what format would you want it in?
@virtualLast same question for you -- what format would you want the whole DB export to be in?

I'm assuming SQL that can be run back-in to a new database as an import.

**Comment by rathboma** [comment] 2023-02-17 18:54
I've taken over this issue to refer to 'export' specifically. I think it's worth making a distinction between backup/restore and export/import.

Export / import - CSV,JSON, etc
Backup / restore - opinionated SQL

**Comment by virtualLast** [comment] 2023-02-17 21:02
Yeah sql would be the easiest

**Comment by afiaudofia** [comment] 2023-02-18 03:13
Yes, SQL format.

**Comment by KeshariPiyush24** [comment] 2023-02-28 12:54
Yes it would be great to have this feature.

**Comment by Santosl2** [comment] 2023-03-04 03:47
Does anyone have any updates?

**Comment by LeoMoshko** [comment] 2023-03-28 17:15
+1

**Closed** 2023-05-29 16:20 UTC

**Comment by david-kariuki** [comment] 2023-05-30 06:37
Is this a TODo or an ongoing development? Is there any update on the same?
