### ISSUE TITLE
BUG: Tables wont load due to "Cannot read properties of null" error

### ISSUE THREAD

**Issue by wouthoekstra** [beekeeper-studio/beekeeper-studio#2640] opened 2024-12-11 14:04 UTC
**Describe the bug**
Tables that up to recently would load properly, now stay blank with a big error: "Error loading data, see error below". This happens to both development and production databases on several servers. The error "below" is, according to the devtools:

```
data fetch error TypeError: Cannot read properties of null (reading 'byteLength')
    at Object.serialize (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:381338:43)
    at opt/Beekeeper Studio/resources/app.asar/dist/utility.js:379868:31
    at Array.forEach (<anonymous>)
    at MariaDBClient.serializeQueryResult (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:379867:40)
    at MariaDBClient.selectTop (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:381770:29)
    at process.processTicksAndRejections (VM33 task_queues:95:5)
    at async conn/selectTop (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:395717:12)
```

It does not happen on all of my tables, some tables do not show an error, but columns remain NULL even though they are not (see screenshot).

**To Reproduce**
I can't entirely make a reproducible error, but I can reproduce the null errors:

Creating a broken table:
```sql
CREATE TABLE `broken_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci
```
Inserting some dummy data:
```
INSERT INTO `broken_second_table` (`id`, `uuid`, `name`) VALUES
(3, 'HIVsRcGKkPFtW', 'lorem'),
(1, 'Qwsogvtv82FCd', 'ipsum'),
(5, 'YnFzw1gLeOb1', 'dolor'),
(2, 'razxDUgYGNAdQ', 'sit'),
(4, 'yhjMzLPhuIDl', 'amet');
```

**Screenshots / Gifs**
**NULL column in broken_table:**
![image](https://github.com/user-attachments/assets/93cc4ecd-f614-491e-907c-473919255943)

**Same data but manually queried:**
![image](https://github.com/user-attachments/assets/37b8cd40-0945-4521-b800-559b71b736f3)

**Entirely broken table:**
![image](https://github.com/user-attachments/assets/62f290e2-1aa4-42b4-8fcc-efa0c2c460e3)

**Version Information (please complete the following information):**
 - OS: Ubuntu 24.04
 - App Version 5.0.6
 - Database type and version: [10.6.18-MariaDB-ubu2004 and 10.6.18-MariaDB]

**Comment by wouthoekstra** [comment] 2024-12-11 14:21
I am pretty sure it has to do with the `utf8mb4_bin` collation. I quickly scanned all my tables, and the ones that have one or more `utf8mb4_bin` columns in it fail to load.

**Comment by rathboma** [comment] 2024-12-11 15:48
Great info, thanks! We'll get right on this. Thank you VERY MUCH for the reproduction steps.

@wouthoekstra is this a new problem with the 5.x release? Was it working in 4.x?

**Comment by wouthoekstra** [comment] 2024-12-11 16:05
Ehm I am not sure which version this started with. Just this week I have updated beekeeper and it has been a while since I had checked for updates before that. In the apt logs I found that I came from version `4.6.8` and I have updated to `5.0.5`. After I got these issues, I've updated again, to `5.0.6`

**Comment by not-night-but** [comment] 2024-12-11 19:05
@wouthoekstra I can confirm that it is related to the `utf8mb4_bin` collation. That makes the mysql driver think it's a binary column, and thus it is run through our binary parser. I'm looking into a fix right now

**Comment by Stokestack** [comment] 2024-12-11 22:51
I just hit this after updating today; not sure what my previous version was, but it wasn't more than a couple weeks old I think.

This table fails:

```
ID	varchar(36)	NO	PRI		
username	varchar(100)	NO	UNI		
pwHash	text	NO			
firstName	text	YES			
lastName	text	YES			
EMail	varchar(100)	YES	UNI		
phoneNbr	varchar(50)	YES	UNI		
avatarURL	text	YES			
mediaServiceID	varchar(36)	YES	MUL		
validated	tinyint(1)	NO		0	
creationDate	datetime	NO		current_timestamp()	
lastSeenDate	datetime	NO		current_timestamp()	
currOTP	varchar(255)	YES			
OTPExpires	datetime	YES	
```

**Comment by rathboma** [comment] 2024-12-12 01:16
@not-night-but please make sure you add a test when you manage to fix this!

**Comment by not-night-but** [comment] 2024-12-12 01:18
@rathboma Of course!

@Stokestack Is there any chance I could get a create script for the offending table? I'm pretty sure this is the same issue, but more data is always helpful.

**Comment by Stokestack** [comment] 2024-12-12 06:00
Sure:

CREATE TABLE User
(
ID VARCHAR(36) NOT NULL UNIQUE ,
username VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL UNIQUE ,
pwHash TEXT NOT NULL,
firstName TEXT COLLATE utf8_unicode_ci,
lastName TEXT COLLATE utf8_unicode_ci,
EMail VARCHAR(100) COLLATE utf8_unicode_ci UNIQUE ,
phoneNbr VARCHAR(50) UNIQUE ,
avatarURL TEXT,
mediaServiceID VARCHAR(36),
validated BOOL NOT NULL DEFAULT false,
creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
lastSeenDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
currOTP VARCHAR(255),
OTPExpires DATETIME,
PRIMARY KEY (ID)
);

**Comment by jancoow** [comment] 2024-12-12 10:34
I'm experiencing the same issue; multiple tables won't load due this error. This all happens with a column 'bytea'  in PostgreSQL

**Comment by jmalvarezf-lmes** [comment] 2024-12-13 09:18
I opened #2644 but I think it is a duplicate of this one. I'm going to close the one I opened. For me it happened with the upgrade from 4.6 to 5.0.6, and continues happening since then.

**Comment by ScripterSugar** [comment] 2024-12-18 06:07
All tables with collation utf8mb4_ui is failing to load after recent update for me too.

**Closed** 2024-12-18 16:35 UTC

**Comment by iatharva** [comment] 2024-12-18 17:16
Just one question, when would this fix be released?

**Comment by molarmanful** [comment] 2024-12-22 04:22
Hi, just wanted to report that I've ran into this error in v5.0.9 on my SQLite tables with the following schema:

```
name TEXT PRIMARY KEY NOT NULL UNIQUE,
code INTEGER NOT NULL,
dwidth INTEGER NOT NULL DEFAULT 0,
is_abs INTEGER NOT NULL DEFAULT 1,
bb_x INTEGER NOT NULL DEFAULT 0,
bb_y INTEGER NOT NULL DEFAULT 0,
off_x INTEGER NOT NULL DEFAULT 0,
off_y INTEGER NOT NULL DEFAULT 0,
img BLOB
```

The error seems to happen when there exists a row in which column `img` is null.

**Comment by not-night-but** [comment] 2024-12-22 04:24
@molarmanful This issue was specifically related to MySQL. If you wouldn't mind, could you file a separate issue for your problem? Just makes tracking easier for me :)
