### ISSUE TITLE
BUG: INTERVAL columns receive wrong value when cloning row

### ISSUE THREAD

**Issue by atrejut** [beekeeper-studio/beekeeper-studio#1442] opened 2022-11-29 15:41 UTC
**Describe the bug**
When `clone`ing a row where a column is of data type `INTERVAL(6)` and committing the new row without touching the field in the interval column, the value in the new row is changed to the shortes (?) possible interval given the original interval (truncating all zeros on the right maybe?).

**To Reproduce**
- Connect to a postgres database (14 in my case, but I think I remember this from using an older postgres version as well)
- create a table where one column is of type `interval`, e.g.
```
CREATE TABLE
  automation.ingestion_config (
    sensor_id uuid NOT NULL,
    mqtt_topic text NOT NULL,
    persist boolean NOT NULL DEFAULT true,
    target_table text NULL,
    expected_frequency interval NULL
  );

ALTER TABLE
  automation.ingestion_config
ADD
  CONSTRAINT ingestion_config_pkey PRIMARY KEY (mqtt_topic)
```
- insert a row in the table
- open the table, right-click on the row and select `clone row`
- (change/set new value for primary key column)
- click `Apply`
- check the new value in the `interval`-type column

**Expected behavior**
the cloned row should have the same value as the source row. 
It seems to me all zeros on the right are removed, e.g. a source value of `00:10:00` (10 minutes) is turned into `00:00:01` (1 second), while a source value of `00:15:00` (15 minutes) is turned into `00:00:15` (15 seconds)...

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version 3.7.2
 - PostgreSQL 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit

**Comment by rathboma** [comment] 2022-12-10 03:13
Thanks for the report!

**Comment by davidkaufman** [comment] 2022-12-26 16:18
Recreated screenie:
![Kapture 2022-12-26 at 11 06 09](https://user-images.githubusercontent.com/2336122/209566988-7c214c5c-f868-4c37-982e-264f04928372.gif)

**Comment by davidkaufman** [comment] 2022-12-31 22:10
Investigating this, I added some debugging code to the `TableTable.vue` component's `buildPendingInserts()` and `cellCloneRow()` functions and found they seemed to be doing exactly what they was supposed to do. The problem is that the way Beekeeper is displaying these intervals, as JSON date-like objects, is not valid when we send it back to postgres as a literal value for an `interval` column:

So for instance in the example above, Beekeeper sent this insert query sent to postgres:
~~~sql
INSERT INTO test_bug1442 (name, frequency) VALUES ('cloned row', ''{"minutes":15}');
~~~
which (annoyingly) postgres silently accepts without error, then simply ignores all the characters except the digits `15` but choosing interpreting those digits as _seconds_.  [PG's "Interval Input" docs](https://www.postgresql.org/docs/15/datatype-datetime.html#DATATYPE-INTERVAL-INPUT) describe the many bizarre ways an "interval literal" can be sent as input, *but json definitely ain't one of em!*

Google was not much help, mostly other users complaining about why knex chooses to represent these as JSON instead of the "native" format, e.g. https://stackoverflow.com/questions/54047682/why-does-selecting-postgresql-interval-using-knex-js-returns-a-json-or-javascrip

Here are some of the examples of interval literals I tested to see if pg would accept, using each of its `IntervalStyle` settings (`postgres`, `postgres_verbose` ,`sql_standard` and `iso_8601`):

### IntervalStyle `postgres` (this is the default)
~~~sql
pg_test=# SET IntervalStyle = postgres;
SET
pg_test=# select * from test_bug1442;
 id |             freq              |                      note
----+-------------------------------+----------------------------------------------------------------------------------
  1 | 00:00:15                      | inserted JSON hours: {"hours":15}
  2 | 00:00:15                      | inserted JSON minutes: {"minutes":15}
  3 | 00:00:15                      | inserted JSON seconds: {"seconds":15}
  4 | 00:00:05                      | inserted garbage ending in 5 "?#!%^&*5}"
  5 | 05:00:00                      | inserted garbage ending in 5:0 "?#!%^&*5:0}"
  6 | 05:00:00                      | inserted garbage ending in :5:0 "?#!%^&*:5:0}"
  7 | 00:05:00                      | inserted garbage ending in 0:5:0 "?#!%^&*0:5:0}"
  8 | 1 year 2 mons 3 days 04:05:06 | inserted all the fields like "1 year 2 months 3 days 4 hours 5 minutess 6 seconds"
  9 | 1 year 2 mons 3 days 04:05:06 | inserted all the fields in Y-M-D H:M:S format "1-2-3 4:5:6"
(9 rows)
~~~

### IntervalStyle `postgres_verbose`
~~~sql
pg_test=# SET IntervalStyle = postgres_verbose;
SET
pg_test=# select * from test_bug1442;
 id |                     freq                     |                      note
----+----------------------------------------------+-------------------------------------------------
  1 | @ 15 secs                                    | inserted JSON hours: {"hours":15}
  2 | @ 15 secs                                    | inserted JSON minutes: {"minutes":15}
  3 | @ 15 secs                                    | inserted JSON seconds: {"seconds":15}
  4 | @ 5 secs                                     | inserted garbage ending in 5 "?#!%^&*5}"
  5 | @ 5 hours                                    | inserted garbage ending in 5:0 "?#!%^&*5}"
  6 | @ 5 hours                                    | inserted garbage ending in :5:0 "?#!%^&*5}"
  7 | @ 5 mins                                     | inserted garbage ending in 0:5:0 "?#!%^&*0:5:0}"
  8 | @ 1 year 2 mons 3 days 4 hours 5 mins 6 secs | inserted all the fields like "1 year 2 months 3 days 4 hours 5 minutess 6 seconds"
  9 | @ 1 year 2 mons 3 days 4 hours 5 mins 6 secs | inserted all the fields in Y-M-D H:M:S format "1-2-3 4:5:6"
(9 rows)
~~~

### IntervalStyle `sql_standard`
~~~sql
pg_test=# SET IntervalStyle = sql_standard;
SET
pg_test=# select * from test_bug1442;
 id |       freq       |                      note
----+------------------+------------------------------------------------------------------------------
  1 | 0:00:15          | inserted JSON hours: {"hours":15}
  2 | 0:00:15          | inserted JSON minutes: {"minutes":15}
  3 | 0:00:15          | inserted JSON seconds: {"seconds":15}
  4 | 0:00:05          | inserted garbage ending in 5 "?#!%^&*5}"
  5 | 5:00:00          | inserted garbage ending in 5:0 "?#!%^&*5:0}"
  6 | 5:00:00          | inserted garbage ending in :5:0 "?#!%^&*:5:0}"
  7 | 0:05:00          | inserted garbage ending in 0:5:0 "?#!%^&*0:5:0}"
  8 | +1-2 +3 +4:05:06 | inserted all the fields like "1 year 2 months 3 days 4 hours 5 minutess 6 seconds"
  9 | +1-2 +3 +4:05:06 | inserted all the fields in Y-M-D H:M:S format "1-2-3 4:5:6"
(9 rows)
~~~

### IntervalStyle `iso_8601`
~~~sql
pg_test=# SET IntervalStyle = iso_8601;
SET
pg_test=# select * from test_bug1442
pg_test-# ;
 id |      freq      |                      note
----+----------------+-------------------------------------------------
  1 | PT15S          | inserted JSON hours: {"hours":15}
  2 | PT15S          | inserted JSON minutes: {"minutes":15}
  3 | PT15S          | inserted JSON seconds: {"seconds":15}
  4 | PT5S           | inserted garbage ending in 5 "?#!%^&*5}"
  5 | PT5H           | inserted garbage ending in 5:0 "?#!%^&*5}"
  6 | PT5H           | inserted garbage ending in :5:0 "?#!%^&*5}"
  7 | PT5M           | inserted garbage ending in 0:5:0 "?#!%^&*0:5:0}"
  8 | P1Y2M3DT4H5M6S | inserted all the fields like "1 year 2 months 3 days 4 hours 5 minutess 6 seconds"
  9 | P1Y2M3DT4H5M6S | inserted all the fields in Y-M-D H:M:S format "1-2-3 4:5:6"
(9 rows)
~~~

None of which helps me resolve the current problem, and I post it only to vent my frustration at the garbage pg will accept for a literal interval value without error, and then happily misinterpret 😡 

But the above did reveal to me the existence of the `postgres_verbose` format which looks *very easy* to translate back and form from our own current (json verbose) format!  

So my first stab at fixing this was to follow on down the rabbit hole, through `saveChanges()` to `lib/db/clients/postgresql.ts`'s `applyChanges()` and `insertRows()` function  to add an `else if` clause into the `insertRows()` function, where it is fixing up `rawInserts` into `fixedInserts` before sending them to postgres:

~~~diff
diff --git a/apps/studio/src/lib/db/clients/postgresql.ts b/apps/studio/src/lib/db/clients/postgresql.ts
index 42b9d19d..058fd5b4 100644
--- a/apps/studio/src/lib/db/clients/postgresql.ts
+++ b/apps/studio/src/lib/db/clients/postgresql.ts
@@ -1028,6 +1038,7 @@ async function insertRows(cli: any, rawInserts: TableInsert[]) {
   const columnsList = await Promise.all(rawInserts.map((insert) => {
     return listTableColumns(cli, null, insert.table, insert.schema)
   }))
+  console.warn('insertRows() rawInserts sql: ', buildInsertQueries(knex, rawInserts))
 
   const fixedInserts = rawInserts.map((insert, idx) => {
     const result = { ...insert}
@@ -1037,6 +1048,15 @@ async function insertRows(cli: any, rawInserts: TableInsert[]) {
         const column = columns.find((c) => c.columnName === key)
         if (column && column.dataType.startsWith('_')) {
           return JSON.parse(value)
+        // } else if (column && column.dataType.startsWith('interval')) { 
+        //   /* a poor man's interval parser */
+        //   const json_interval = JSON.parse(value)
+        //   const interval_units = []
+        //   Array('years','months','days','hours','minutes','seconds').forEach( unit => {
+        //     if (json_interval[unit]) interval_units.push(json_interval[unit] + ' ' + unit )
+        //   })
+        //   const pg_format_interval = interval_units.join(' ')
+        //   return pg_format_interval
         } else {
           return value
         }
@@ -1044,6 +1064,7 @@ async function insertRows(cli: any, rawInserts: TableInsert[]) {
     })
     return result
   })
+  console.warn('insertRows() fixedInserts sql: ', buildInsertQueries(knex, fixedInserts))
   await driverExecuteQuery(cli, { query: buildInsertQueries(knex, fixedInserts).join(";") })
 
   return true
~~~

And this seemed like a cool solution, obviously converting all of the JSON units e.g. `{"minutes":15}` into `15 minutes` just in time into what seems to be the least ambiguous (and easiest to read!) format pg accepts, and in just 9 lines of code! 😀 

And that works, resolving the bug reported, but _*ONLY*_ for the clone (insert json) use case.  But it feels like kindof a hacky kludge, that would need to be refactored into its own function so it could be shared by (at least) the `updateRows` function too.  And surely there would be many other places where this odd data-type munging would come back to bite us again and again down the road.

**Comment by davidkaufman** [comment] 2022-12-31 22:49
So I dug deeper, thinking this was a very similar issue to the way pg handles datetimes & timestamps, and wondering why is it so hard?  And (finally) found this gh issue (from 2013!) in the `node-postgres` module:

- https://github.com/brianc/node-postgres/issues/285

And discovered that _**Beekeeper is already using this ~solution~ workaround**_ (apparently @brianc never got around to documenting this better "soon" lol):

`vim apps/studio/src/lib/db/clients/postgresql.ts`
~~~ts
  47 /**
  48  * Do not convert DATE types to JS date.
  49  * It ignores of applying a wrong timezone to the date.
  50  * TODO: do not convert as well these same types with array (types 1115, 1182, 1185)
  51  */
  52 pg.types.setTypeParser(1082, 'text', (val) => val); // date
  53 pg.types.setTypeParser(1114, 'text', (val) => val); // timestamp without timezone
  54 pg.types.setTypeParser(1184, 'text', (val) => val); // timestamp
~~~

And then I had a heck of a time finding what the magic `setTyeParser` number is, for an interval column. He mentions:

@brianc wrote:
> Here are the default type parser configurations:
> https://github.com/brianc/node-postgres/blob/master/lib/textParsers.js#L166

But that module doesn't exist in our `node_modules`  dir 🤔  -- then found that's apparently because, at some point between 2013 and now, the `node-postgres` was renamed `pg` and the types were moved into their own separate `node-pg-types` module, so I finally found them in https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js#L175 

and what I ended up with was:

~~~diff
diff --git a/apps/studio/src/lib/db/clients/postgresql.ts b/apps/studio/src/lib/db/clients/postgresql.ts
index 42b9d19d..058fd5b4 100644
--- a/apps/studio/src/lib/db/clients/postgresql.ts
+++ b/apps/studio/src/lib/db/clients/postgresql.ts
@@ -47,11 +47,17 @@ function tableName(table: string, schema?: string): string{
 /**
  * Do not convert DATE types to JS date.
  * It ignores of applying a wrong timezone to the date.
+ *
+ * See also: https://github.com/brianc/node-postgres/issues/285
+ * (and note that the code refrenced in /lib/textParsers.js has been broken out into it own module
+ * so it now lives in https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js#L175)
+ *
  * TODO: do not convert as well these same types with array (types 1115, 1182, 1185)
  */
 pg.types.setTypeParser(1082, 'text', (val) => val); // date
 pg.types.setTypeParser(1114, 'text', (val) => val); // timestamp without timezone
 pg.types.setTypeParser(1184, 'text', (val) => val); // timestamp
+pg.types.setTypeParser(1186, 'text', (val) => val); // interval (Issue #1442 "BUG: INTERVAL columns receive wrong value when cloning row)
 
 /**
  * Convert BYTEA type encoded to hex with '\x' prefix to BASE64 URL (without '+' and '=').
~~~

And this "fixes" the problem too!  And is better, since it's just a ONE line code change, and also better because now we don't have to always remember to convert interval values we take from the UI, from json to "postgres_verbose" right before we send them to the database.

But it does have possible drawbacks:  With this, interval values will no longer appear, _**or get exported**_, in the json-friendly format we show and export now.  But I think those relatively few users who use pg's `interval` column type (like the reporter of this bug) won't mind that somewhat-breaking change, and might even prefer to see Beekeeper displaying interval values using the PG syntax that they're familiar with.

So I'm submitting a PR with the one-line code change above (plus its 5 lines of comments)

But I'd be happy to go the other route too, if users would rather keep seeing the JSON-intervals in the UI, and in their exports

**_...or even make this an option_** on the PG-connection screen to toggle between "native pg interval syntax" and "JSON interval syntax"

**Comment by atrejut** [comment] 2023-01-01 11:05
Hey guys,

thanks for looking into this! Just wanted to mention, I'm pretty neutral on whether intervals are displayed as json or not, and personally would have no problem with the 'breaking' change. Since I'm here there's actually another oddity in sorting interval columns that might also be taken care of if the format changes -- see screenshot (the fourth entry of 27mins is in the wrong place). [If you'd like to have a separate issue for that I'd be happy to create one as well, but thought it might be better to bring it up here first :) ]

![image](https://user-images.githubusercontent.com/6804206/210168243-2f1a908d-fd68-4733-b89f-05e55396ba23.png)

**Comment by davidkaufman** [comment] 2023-01-01 21:40
@atrejut said
> there's actually another oddity in sorting interval columns that might also be taken care of if the format changes -- see screenshot (the fourth entry of 27mins is in the wrong place). [If you'd like to have a separate issue for that I'd be happy to create one as well, but thought it might be better to bring it up here first :) ]

That would definitely be a separate bug (or feature request) since, after this change, it's still doesn't sort quite right:
![image](https://user-images.githubusercontent.com/2336122/210185333-1c15bfb9-670a-4e63-909e-2d9f4738a242.png)

**Comment by atrejut** [comment] 2023-01-02 08:15
ah yes, didn't think about anything longer than hours of course :)
created #1466

**Closed** 2023-01-13 15:40 UTC
Labels: bug, accepted :+1:
