### ISSUE TITLE
Slow data load times with fairly wide datasets

### ISSUE THREAD

**Issue by hjone72** [beekeeper-studio/beekeeper-studio#135] opened 2020-05-19 22:12 UTC
Testing out the software because it looks really nice! I've found that it is very slow to open larger databases and quite slow to execute and render queries.

1200+ tables took over a minute to load
7879 results took around 7 seconds, compared with azure data studio which took less than 3.

Not sure if this can be resolved :) Really nice work so far!

**Comment by rathboma** [comment] 2020-05-20 21:20
Oh, these can definitely be resolved :-)

The table loading should be much faster, but there was a bug in the SSH tunnel that prevented multiple connections. Hopefully will be fixing that soon.

Question on the results 
-- This was SQL Server?
-- Presumably this was a custom SQL query?
-- how wide is your result set?

**Comment by hjone72** [comment] 2020-05-20 23:38
Thanks for the reply. Looking forward to trying to bug fixed version :)

Yeah it is an MS SQL Server.
It was a pretty basic SQL query haha.
```
Select *
FROM table
```
Only about 8000 rows and 20 columns. It's not tiny, but far from massive. I'm using Azure Data Studio for comparisons and it handles the query in about 3 seconds.

Cheers,

**Comment by rathboma** [comment] 2020-05-22 18:13
I'll be pushing out a new version soon, that should improve the table loading speed significantly. The 20 column query results will take a little more work, but will definitely get to it :-)

**Comment by rathboma** [comment] 2020-05-23 02:18
V1.4 is out -- should improve table load times quite significantly

In terms of slow time to load the table. I suspect it's rendering the dataset (not the actual fetching of the data) that is causing the slow down. I'll look into how this could be improved -- I suspect lots of wide columns cause the table library some pain

**Comment by gnovaro** [comment] 2020-06-04 08:57
I have had the same problem with a big mysql table and the program abruptly closed

**Comment by rathboma** [comment] 2020-06-04 13:59
@gnovaro can you give me a few more details -- how wide / long was the dataset? eg 100 columns, 10000 records.

What view were you in? SQL editor or table-tab?

**Comment by gnovaro** [comment] 2020-06-05 09:43
I think columns no more than 16, but 50.000 records or more.

**Comment by pvanhemmen** [comment] 2020-06-23 21:12
I can confirm these slow load times on average sized to big tables (~ 500.000 entries). Trying to open a bigger table from the tables & views panel on the left hand side not only takes quite some time to load but also drastically slows down the application and the whole interface (for example switching forth and back between a query tab and the results tab).
Do the queries used for display have a (configurable) default limit set? This is how I think most of the gui tools out there handle performance decreases when displaying big tables.

I'm on Ubuntu 20.04 with the latest snap version 1.5.3 installed.

**Comment by rathboma** [comment] 2020-06-23 21:36
Hey @pvanhemmen,

Thanks for reporting. Hoping you can give me some information:

1. How many tabs do you have open?
2. Query tabs -- how many results displayed?
3. Table tabs -- how many table tabs?


The table-tabs only pull back the first page of records, then page in results as you navigate the table.

The query tab just loads your whole result-set (upto ~100k records I think). I need to change this to behave more like the table tabs to be honest.

**Comment by pvanhemmen** [comment] 2020-06-23 22:26
Hey @rathboma ,

I had just the results tab from the table view open and an empty query tab (with no query sent). So I investigated some more and the problem seems to be more related to the amount of columns within the displayed result. I have a table with ~ 150 columns and this seems to slow down the application even with just 10 entries selected. Limiting to 100 or even 1000 makes beekeeper nearly unresponsive. The more data is being displayed, the slower it gets. Maybe this is due to rendering issues with angular caused by too many data bindings?

**Comment by pvanhemmen** [comment] 2020-06-23 22:29
Just read your comment above from 05/23 again and yes, I think that's the culprit.

**Comment by rathboma** [comment] 2020-06-23 22:32
Yep for sure. I think I need to move to a different table library or figure out how to get tabulator to better deal with many columns

**Comment by pvanhemmen** [comment] 2020-06-23 22:33
Alright, thanx for taking the time and for your efforts!

**Comment by pvanhemmen** [comment] 2020-06-23 22:36
Maybe have a look into datatables. I remember that library having a feature called deferred rendering. Seems it is still implemented: https://datatables.net/examples/ajax/defer_render.html

**Comment by MrBretticus** [comment] 2020-08-26 00:47
Can confirm that I am also seeing significant slow down on wide tables, in my case 171 columns (even if selecting only the top 10 rows for example).

Only have the one query tab open.

**Comment by rathboma** [comment] 2020-08-26 03:07
Yep! I'm in regular contact with Oli from Tabulator, version 4.8 should help a bunch, the full 5.0 release will fix it for good.

**Comment by rathboma** [comment] 2020-09-17 18:48
This is fixed in master branch. Will be in the next release. I have tested with 500 columns - 0.3 second load time!

**Closed by rathboma** 2020-09-17 18:48 UTC
Labels: bug, ui/ux

**Comment by MrBretticus** [comment] 2020-10-27 04:47
Can confirm this is working well, thank you
