### ISSUE TITLE
hard link installation error

### ISSUE THREAD

**Issue by matte78** [beekeeper-studio/beekeeper-studio#659] opened 2021-05-19 13:21 UTC
**Describe the bug**
Unpacking beekeeper-studio (1.11.3) ...
dpkg: error processing archive /var/cache/apt/archives/beekeeper-studio_1.11.3_amd64.deb (--unpack):
 error creating hard link './usr/share/icons/hicolor/24x24/apps/beekeeper-studio.png': Invalid cross-device link
Errors were encountered while processing:
 /var/cache/apt/archives/beekeeper-studio_1.11.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**To Reproduce**
apt install beekeeper-studio

**Version Information (please complete the following information):**
 - OS: Ubuntu Focal
 - App Version 1.11.3

**Additional context**
I have a standard installation with multiple partition
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p5   23G   19G  2,8G  88% /
/dev/nvme0n1p6  9,2G  4,2G  4,5G  49% /var
/dev/nvme0n1p8  1,9G  5,8M  1,7G   1% /tmp
/dev/nvme0n1p9  335G   79G  239G  25% /home

**Comment by rathboma** [comment] 2021-05-20 01:47
Yes. This is a problem with the way electron-builder packages apps. Currently the workaround is to use AppImages unfortunately.

There is a way to fix it, but I haven't had the time yet :-(. It only happens if /opt and /var are on different disks. Duplicate of #593.

Closing this as it's a duplicate, but I'm tracking it.

**Closed by rathboma** 2021-05-20 01:47 UTC

**Comment by matte78** [comment] 2021-05-21 10:51
ok but....
![image](https://user-images.githubusercontent.com/58658630/119126392-45147880-ba33-11eb-99a7-fce421624745.png)

**Comment by yogesch** [comment] 2021-05-25 18:17
> Yes. This is a problem with the way electron-builder packages apps. Currently the workaround is to use AppImages unfortunately.
> 
> There is a way to fix it, but I haven't had the time yet :-(. It only happens if /opt and /var are on different disks. Duplicate of #593.
> 
> Closing this as it's a duplicate, but I'm tracking it.

Not just /opt and /var but it seems if any of the involved directories are on a different disk. I have /, /usr, /home, on different disks and run into this exact issue. Fortunately, I am not the first.

**Comment by donuts-are-good** [comment] 2022-01-30 01:15
Issue still persists
