### ISSUE TITLE
FEAT: Create native M1 electron version

### ISSUE THREAD

**Issue by LorenzoSapora** [beekeeper-studio/beekeeper-studio#903] opened 2021-12-03 15:10 UTC
**Is your feature request related to a problem? Please describe.**

Beekeeper isn't native on M1 macs.

**Describe the solution you'd like**

Use electron's native mode for m1(+) macs. While I have no problem with the universal binary, running on rosetta isn't optimal. 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Likenttt** [comment] 2021-12-06 06:44
I cannot build it on macos m1 now

**Comment by LorenzoSapora** [comment] 2021-12-07 10:42
Hot dang, that's a lot of build errors. I believe this is because beekeeper is using 12.1.0 whereas 13.x.x has some of the needed tweaks. Also, electronjs is now at 16.x.x (stable) and 18.x.x (edge).

**Comment by rathboma** [comment] 2021-12-20 19:23
Hey! AWS just released their M1 mac instances. I've applied for access to the preview. Once I get access I'll start working to create the first M1 build.

Given the 'speed' that AWS moves at, I'd expect sometime in Jan

**Comment by rathboma** [comment] 2021-12-20 19:24
Duplicate of #599 

Closing due to duplicate. But I'll be on this in the New Year for sure :-)

**Closed by rathboma** 2021-12-20 19:24 UTC
