### ISSUE TITLE
BUG: Action Bar doesn't appear

### ISSUE THREAD

**Issue by bogu399** [beekeeper-studio/beekeeper-studio#1131] opened 2022-03-31 13:47 UTC
**Describe the bug**
I have installed the software but the Action Bar doesn't appear to me. How could I solve this?

**Expected behavior**
I would see the Action Bar

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/18585098/161069122-0ac9a8e2-c722-4c55-a1c9-0df97ee3afbf.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version Beekeeper Studio 3.3.6
 - Database type and version MariaDB 10.7.3

**Comment by rathboma** [comment] 2022-03-31 14:18
I think the native menus are broken on windows. I'll take a look at it today. Sorry about this. If you do wngrade to the previous version that will work as a workaround

**Comment by IndrekHaav** [comment] 2022-04-01 12:08
Duplicate of #1123 (there's also a workaround in that issue).

**Comment by rathboma** [comment] 2022-04-01 15:05
Hey! I've fixed this and will be making a point release later today

**Closed by rathboma** 2022-04-01 15:05 UTC
