### ISSUE TITLE
BUG: Locking when loading list of databases

### ISSUE THREAD

**Issue by cyberh3x** [beekeeper-studio/beekeeper-studio#2065] opened 2024-03-29 19:48 UTC
Hi
When I click on a database connection, App locked in loading databases
I updated this app to latest version but this bug not fixed.

OS: `Ubuntu 22.04.4 LTS 64-bit`
Beekeeper Studio Version: `4.2.5`

[Screencast from 24-03-29 23:14:39.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/42694294/992f6826-9920-4192-98c9-c0d985aade38)

**Comment by rathboma** [comment] 2024-03-29 21:11
Hey! Yeah we've seen this issue. I recommend downgrading for now, we're working on a fix. I think it's a race condition in the DB driver. Duplicate of #2061

**Closed by rathboma** 2024-03-29 21:11 UTC
