### ISSUE TITLE
FEAT: Allow users to read files from the file system

### ISSUE THREAD

**Issue by mjkanji** [beekeeper-studio/beekeeper-studio#985] opened 2022-01-19 17:53 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to read .sql files from the disk into Beekeeper Studio. Ideally, there should be a file explorer like VS Code so we can open a folder/workspace into Beekeeper. I'd ideally like to manage my queries as a git repo instead of just saving them in Beekeeper.

**Describe the solution you'd like**
Described above.

**Describe alternatives you've considered**
Copy/pasting saved queries into a separate file, but that starts to get tedious quickly.

**Additional context**
None.

**Comment by rathboma** [comment] 2022-01-24 23:42
Yes, I do agree this is a gap in the application.

Right now the best way to get them INTO beekeeper is to drag / drop into a query editor window.

I'm going to think about the best way to integrate file exploration. Thanks so much for filing an issue.

Closing due to duplicate, but I do care about this feature!
Duplicate of #617 
Duplicate of #256

**Closed by rathboma** 2022-01-24 23:42 UTC
