### ISSUE TITLE
BUG: Table contents disappear as I scroll right.

### ISSUE THREAD

**Issue by cthulhu-of-vhoorl** [beekeeper-studio/beekeeper-studio#445] opened 2020-11-16 11:35 UTC
**Describe the bug**
When I query a table with a lot of columns and look through the output, as I scroll right I hit a point where the whole table view blanks out.  I can scroll back to the left and it'll reappear, but it basically means that I cannot see the rightmost columns of queries with a lot of columns.

**To Reproduce**
1. Connect to a database (I'm using Postgres across an ssh tunnel if that matters).
2. Run `select * from <table_name> limit 100` on any table with too many columns to be displayed in the table view without scrolling to the right.
3. Scroll to the right until the contents of the table view disappear.

**Expected behavior**
Scrolling left and right should not do this.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 1.8.7

**Comment by rathboma** [comment] 2020-11-17 18:32
Hey! Thanks for the bug report. I'll take a look at it.

**Comment by rathboma** [comment] 2020-11-17 19:23
@cthulhu-of-vhoorl can you record a screengrab (gif or vid are best)? I'm having trouble replicating this issue.

**Comment by cthulhu-of-vhoorl** [comment] 2020-11-18 04:15
@rathboma sure thing.  https://imgur.com/a/yxaguKC

**Comment by rathboma** [comment] 2020-11-18 14:06
Great thank you!

**Comment by cthulhu-of-vhoorl** [comment] 2020-11-22 06:07
Here's an example query where this happens so you can test it out.

```sql
with cte (col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16, col17) as (
values (1885013, '2017-01-05 14:09:39.564693+00', '2018-04-12 15:08:49.959803+00', 2666917, 12082424, TRUE, 'c7hy74bd7-80ab-494b-b1a9-35a93ft1b090a', TRUE, TRUE, TRUE, FALSE, 7294256, 1, 0, null, 1, FALSE),
(2863015, '2018-09-26 15:08:30.988371+00', '2018-09-27 21:18:46.263226+00', 4082519, 12154536, TRUE, '6g3de4f3-442b-4803-a519-57973gsdee35dc', TRUE, TRUE, TRUE, FALSE, 10892533, null, 5, null, 1, TRUE),
(330718, '2011-08-27 11:40:49.417935+00', '2018-08-09 13:36:34.632721+00', 353013, 12245, TRUE, '25cdffd6-7cb6-45d9-916c-e5e1a6dgd55e', TRUE, TRUE, TRUE, FALSE, null, 226, 0, null, 1, FALSE),
(69218, '2010-11-23 04:00:29.004836+00', '2010-11-23 04:00:29.232682+00', 82014, 149, FALSE, 'd6g7656b-af5f-4cb4-8f20-dds235h055b71', FALSE, FALSE, FALSE, FALSE, null, null, 0, null, 1, FALSE),
(698712, '2014-02-14 17:55:47.384475+00', '2014-02-14 17:56:08.074771+00', 632414, 1319238, FALSE, '3f5647ed-df82-4f95-a354-4sd344e0a9a8', FALSE, TRUE, FALSE, FALSE, 1692544, null, 0, null, 1, FALSE)
)
select * from cte;
```

**Comment by Brunorio** [comment] 2021-01-08 12:16
![image](https://user-images.githubusercontent.com/32521472/104013773-b6444500-5190-11eb-8976-10db6d947bfe.png)
A have same problem, when i run my query i can see normally the table contents but when scroll to right contents disappear. Backing to left, contents appear again
If resize the window, Table contents appear (without execute another query), but if i execute again a query with window resized and scroll to left, contents disappear too

**Comment by rathboma** [comment] 2021-01-08 17:48
@olifolkerd have you seen anything else like this with Tabulator in the past? I'm not able to reliably replicate this.

@Brunorio can you try resizing your window to see if it still happens?

**Comment by rathboma** [comment] 2021-01-18 17:23
@Brunorio and @cthulhu-of-vhoorl can you test the build here:
https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/494117549

and let me know if the issue is fixed?

Matthew

**Comment by Daninet** [comment] 2021-01-23 22:12
I just found out that this issue is the same I for which I created this issue: https://github.com/beekeeper-studio/beekeeper-studio/issues/524

@rathboma I tested the portable windows build from here: https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/494117549, but nothing has changed. The rows still disappear with horizontal scroll.

**Comment by rathboma** [comment] 2021-01-23 22:21
Yeah, I also saw it again. I'm working on it with the maintainer or tabulator. It's a really tricky issue!

**Comment by rathboma** [comment] 2021-01-31 19:22
This is fixed in master by disabling the horizontal dom for the timebeing

**Closed by rathboma** 2021-01-31 19:22 UTC
Labels: accepted :+1:, bug, need-more-info :grey_question:
