### ISSUE TITLE
FEAT: View Structure result Columns show the column's comment.

### ISSUE THREAD

**Issue by dongzl** [beekeeper-studio/beekeeper-studio#1108] opened 2022-03-22 06:13 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

View Structure result Columns show the column's comment.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/5917359/159418903-d4201bf7-fe0e-4f94-bd3a-38ef74e1d70c.png">

I think column comment is important, show the comment is suitable, Thanks.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)

**Database type, if appropriate**
Does this feature only relate to a specific type of database? (eg Postgresql)
`MySQL`

**Comment by rathboma** [comment] 2022-04-22 18:31
Yes this will come soon!

Duplicate of #722

**Closed by rathboma** 2022-04-22 18:31 UTC
