### ISSUE TITLE
BUG: Table layout broken when horizontal scrolling is required

### ISSUE THREAD

**Issue by Daninet** [beekeeper-studio/beekeeper-studio#524] opened 2021-01-23 22:02 UTC
**Describe the bug**
Table layout calculation is broken, when horizonal scrolling is required: the results disappear completely or the columns will not match the X coordinate of the matching table header. See the attached gif.
There is a unreliable workaround to slightly modify the sidebar width. Once it is modified the layout starts working again, but not always.

I reproduced it with Postgres and SQLite, but it is probably engine independent.

**To Reproduce**
Execute following SQL:
```sql
CREATE TABLE main (
  id integer NOT NULL,
  cid integer NOT NULL,
  key text NOT NULL,
  label text NULL,
  ord integer NULL,
  listid integer NULL,
  percentage integer NULL,
  modified integer NULL
);

INSERT INTO main VALUES(1,2,'long text long text long text long text long text','long text long text',5,6,7,8)
```
2. Open the table
3. Drag the horizontal scrollbar with the mouse
4. Results will disappear. On other larger tables I also seen misplaced result columns.

**Expected behavior**
The results shouldn't disappear. Result columns should match the columns from the header.

**Screenshots / Gifs**
![sqlbroken](https://user-images.githubusercontent.com/884882/105614939-5d51ef00-5dd5-11eb-9a79-ed50e9c1601c.gif)

By looking at the CSS, there is a weird padding, which causes the rows to go out of the viewport:
![sqlbroken2](https://user-images.githubusercontent.com/884882/105615195-6cd23780-5dd7-11eb-96c6-24302e95d73a.gif)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version 1.9.1
- Native window size: 1464x1083 pixels on 4k monitor with 150% scaling

**Comment by Daninet** [comment] 2021-01-23 22:24
One more video showing the column displacement issue:
![sqldisp](https://user-images.githubusercontent.com/884882/105615576-67c2b780-5dda-11eb-9387-931551746c05.gif)

I didn't manage to reproduce this with a smaller table yet.

**Comment by joshuapack** [comment] 2021-01-26 19:13
I am also getting this issue.

OS: MacOS Big Sur 11.1 (intel)
App Version 1.9.1

**Comment by rathboma** [comment] 2021-01-30 17:57
I have a fix coming this weekend.

So sorry about this. It's the vdom implementation of the table component we are using.

**Comment by junkystu** [comment] 2021-02-05 07:07
I'm also experiencing this on Ubuntu 20.04.2 with v1.9.2

**Comment by Daninet** [comment] 2021-02-05 07:50
It became a bit more stable now, but the issue with disappearing rows and misplaced columns are still present in v1.9.2

**Comment by Daninet** [comment] 2021-02-05 17:21
Here is a demo with v1.9.2.
![displacement2](https://user-images.githubusercontent.com/884882/107065816-e0b40d00-67e5-11eb-846e-3978bacbb301.gif)

Database: SQLite Sakila sample https://github.com/ivanceras/sakila/tree/master/sqlite-sakila-db

On the video you can see two things:
1. Horizontal scroll changes row X positions, but the header stays fixed. In this example it is a minor issue, but I also seen cases where the header columns were misplaced by hundreds of pixels in such way that you cannot tell anymore which column is which.

2. Sometimes the table layout breaks completely.
Usually it happens randomly, but I've found a way to consistently reproduce it: 
- Open Sakila sample db.
- Click on the `payment` table twice (it opens two tabs)
- Go to the first tab
- You can see that the result column positions are completely wrong.

It also happens randomly with a single tab open, especially when there are many columns in the table.

**Comment by rathboma** [comment] 2021-02-05 18:07
uck, oh man. I'll take a look. I think we need to call refresh on tabulator or something like that.

**Comment by rathboma** [comment] 2021-02-08 02:07
Ok, this is fixed in the upcoming 1.9.4 release. It's because I'm doing some fancy stuff to update tabs when table columns change.

**Comment by rathboma** [comment] 2021-02-08 19:00
Please take a look - I'm not able to replicate this any more, but @ghstng can. Can anyone confirm one way or the other?

**Comment by joshuapack** [comment] 2021-02-08 19:13
> Please take a look - I'm not able to replicate this any more, but @ghstng can. Can anyone confirm one way or the other?

I am unable to reproduce on windows.

On Mac, I am seeing the header lag when scrolling horizontally only when using the 2 finger swipe. When scrolling by using the horizontal scrollbar, it looks to work fine, just the whole table seems to lag, but the header stays correctly.

**Comment by Daninet** [comment] 2021-02-08 20:29
I don't see broken layouts anymore, but now it is super laggy when scrolling larger tables with many columns.

**Comment by junkystu** [comment] 2021-02-09 06:50
Ubuntu with v1.9.4 looks good now. I'm not noticing any additional lag with large tables (> 2 mil rows) and many columns (9). I said additional because there's always been some lag, with larger tables, followed by the "Loading" screen. Thank you for the fix!

**Comment by gokulprathin8** [comment] 2022-02-06 08:37
On macOS, column name updates with some delay, after data is scrolled horizontally. 

I have 15 columns and I try to horizontally scroll and it feels laggy. when the column name matches correctly after a delay.

**Comment by rathboma** [comment] 2022-02-07 17:50
I got a bug fix for this coming soon, been debugging with the tabulator maintainer. :+1:

**Comment by rathboma** [comment] 2022-02-21 17:04
I'm closing this as it relates to broken layout, but I'm fixing slow rendering of large tables for the next release :muscle:

**Closed** 2022-02-21 17:03 UTC
