### ISSUE TITLE
BUG: An error occurred with the characters

### ISSUE THREAD

**Issue by cuikho210** [beekeeper-studio/beekeeper-studio#922] opened 2021-12-19 18:34 UTC
![image](https://user-images.githubusercontent.com/86552587/146686480-cec031e5-b3d0-41a1-8103-0a186e341997.png)

I press create a table, then I don't want to create any more and close the current tab. A window pops up but no text at all. Looks like an error has occurred with the characters.

This is just a small error and I can still understand it after trying to press 1 of the 2 buttons above, but it looks ugly. The same goes for `Help > About`

I am using Ubuntu 20.04. And these are the fonts I use
![image](https://user-images.githubusercontent.com/86552587/146686721-01174a9e-b146-40e3-acd8-9a8fb2ce3834.png)

**Comment by rathboma** [comment] 2022-01-17 02:34
Ah! I think you are using the `snap` version of the app right? There's some bug with the snap version that causes this. Please try downloading the AppImage or DEB version instead, that should work without this issue, so sorry!

Duplicate of #695

**Closed by rathboma** 2022-01-17 02:34 UTC
