### ISSUE TITLE
FEAT: Show create table sql or tabel structure like Sequel

### ISSUE THREAD

**Issue by vitahlin** [beekeeper-studio/beekeeper-studio#417] opened 2020-10-26 03:12 UTC
**Is your feature request related to a problem? Please describe.**
Show create table sql or tabel structure like Sequel

**Comment by rathboma** [comment] 2020-10-26 13:47
Yep! We'll be working on this soon. duplicate of #310 and #337 .

Going to close this as we're tracking and will prioritize this soon :-)

**Closed by rathboma** 2020-10-26 13:47 UTC
