### ISSUE TITLE
BUG: Cannot restore database in the 4.2.9 version

### ISSUE THREAD

**Issue by aarbmx6s** [beekeeper-studio/beekeeper-studio#2092] opened 2024-04-06 09:14 UTC
**Describe the bug**
After upgrading to the 4.2.9 version, the restore tool fails with:

```
pg_restore: connecting to database for restore
pg_restore: error: connection to database "db" failed: FATAL: password authentication failed for user "user"
``` 
The restoring works fine for the 4.1.13 version.

Commands to perform restoring are identical:

```
path/to/pg_restore --verbose --username=user --host=localhost --port=5432 --no-privileges --clean --create --dbname=db path/to/backup-2024-04-02-local.tar
```

**To Reproduce**
1. Upgrade to the 4.2.9 version
2. Try to restore a backup

**Expected behavior**
The database will be restored from the backup

**Version Information (please complete the following information):**
 - OS: Mac M1
 - App Version 4.2.9
 - Database postgresql 13

**Comment by not-night-but** [comment] 2024-04-08 17:23
Hey! Thanks for the report!

Did some looking around and found the issue, this was caused by a fix to password quoting for mysql :facepalm: 

It's fixed now and should hopefully be in the next release, you can track this issue to see when it's merged

**Closed** 2024-04-12 19:36 UTC
