### ISSUE TITLE
BUG: Not entity column '_connectionType' was found

### ISSUE THREAD

**Issue by Likenttt** [beekeeper-studio/beekeeper-studio#948] opened 2022-01-04 03:44 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/26034018/148006719-faaccaf9-abd5-4174-b706-baaa127c74ce.png)

**To Reproduce**
1. Connect to a db
2. Click  left bottom `Edit Connection`
3. Change the color of current connection
4. Click save, the error will occur

**Expected behavior**

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]

**Additional context**
Anything else you think might be helpful

**Comment by Dominiquini** [comment] 2022-01-04 04:56
Maybe duplicate of https://github.com/beekeeper-studio/beekeeper-studio/issues/949

**Comment by rpsu** [comment] 2022-01-04 14:16
I think this is not a duplicate (commented on https://github.com/beekeeper-studio/beekeeper-studio/issues/949#issuecomment-1004843326). 

Error `Not entity column '_connectionType' was found` happens when all fields (even if not visually set to required) are filled. I 
- edited an existing connection and tried to save it
- opened an existing connection and tried to save it with no changes
- started to create a new connection the message is immediately visible (probably from the earlier errors, which are not cleared when `+ New Connection` button above connections list is clicked).

MacOS 12.1, Beekeeper studio 3.0.1

**Comment by rathboma** [comment] 2022-01-04 14:31
Ok, I'm taking a look now. Thanks for reporting

**Closed** 2022-01-04 15:02 UTC

**Comment by Likenttt** [comment] 2022-01-05 06:41
> Ok, I'm taking a look now. Thanks for reporting

I found this problem is fixed after the latest update. Thanks.

**Comment by rpsu** [comment] 2022-01-05 08:15
cheers, v3.0.3 fixed this 🙇
