### ISSUE TITLE
Bug when clicking table forwarding

### ISSUE THREAD

**Issue by RenanAraujoLima** [beekeeper-studio/beekeeper-studio#1225] opened 2022-05-16 14:30 UTC
**Details:**
The button that forwards to the value source table stopped working after the last updates. I'm clicking but it doesn't work. I have this error after updating, to use this function again I downloaded a previous version, version 3.2.1
![bug](https://user-images.githubusercontent.com/77083419/168616414-00183a5e-1984-4846-b909-385d580db087.gif)

**Version Information**
Operating System: Windows 10
App Version: 3.4.2
Database type and version: MySQL 8.0.26

**Screenshot / GIF [if appropriate]**:
attached gif

**Comment by devinvb** [comment] 2022-05-18 08:42
Duplicate of #1220

**Comment by rathboma** [comment] 2022-05-20 14:23
Fixed in upcoming release

**Closed by rathboma** 2022-05-20 14:23 UTC
