### ISSUE TITLE
Text of dialog windows not showing

### ISSUE THREAD

**Issue by blackforestcode** [beekeeper-studio/beekeeper-studio#598] opened 2021-03-19 09:27 UTC
### Snap Version 1.9.4

I want to add a SQLite connection.

If I click "Choose File" the dialog window doesn't show the text of the files/folders:

![beekeeper1](https://user-images.githubusercontent.com/10848785/111758905-527b7e00-889d-11eb-848b-b18069d39dac.png)

The same error appear if I click on "Help" -> "About Beekeeper Studio":

![beekeeper2](https://user-images.githubusercontent.com/10848785/111759060-7ccd3b80-889d-11eb-9196-411f1a2692cb.png)

**Comment by rathboma** [comment] 2021-03-19 14:47
This is a problem with the Snap version of the app. Can you try the AppImage or DEB version?

There's a possible fix at the snap level, which I hope to work on next week.

**Comment by rathboma** [comment] 2021-03-19 14:47
Duplicate of #32

**Closed by rathboma** 2021-03-19 14:47 UTC
