### ISSUE TITLE
QUESTION: Settings?

### ISSUE THREAD

**Issue by hogensonm** [beekeeper-studio/beekeeper-studio#754] opened 2021-08-04 17:18 UTC
**Details:**
It seems like I'm missing something really obvious but where are the settings?  Are there settings?

**Version Information:**
Operating System: macOS 10.14.6
App Version [help -> about]: 1.13.2

**Comment by hogensonm** [comment] 2021-08-04 17:22
I found an option in the view menu to change the theme but not to change the font colors, for example.  I find the default colors hard to read.  The rest of the app is amazing but I would like to see more customization options.

**Comment by hogensonm** [comment] 2021-08-04 19:26
Also, is there a place to change key bindings?

**Comment by rathboma** [comment] 2021-09-14 19:02
Yes! They'll be coming I promise. We just haven't had time to do them yet.

Duplicate of #197 <- add stuff to here you want to see in settings!

**Closed by rathboma** 2021-09-14 19:02 UTC
