### ISSUE TITLE
FEAT: Flatpak distribution

### ISSUE THREAD

**Issue by LabRat2193** [beekeeper-studio/beekeeper-studio#480] opened 2020-12-20 19:11 UTC
Hi, 

Is there any plan to add flatpak support ?

**Comment by GammaGames** [comment] 2020-12-23 18:09
#22

**Comment by rathboma** [comment] 2020-12-23 22:37
Hey! I'd love to, but I don't think [Electron Builder](http://electron.build) supports flatpak yet. If someone submits a patch I'll happily merge it, but lack the time and expertise to do this right now.

Closing this issue due to duplicate of #22

**Closed by rathboma** 2020-12-23 22:37 UTC
