### ISSUE TITLE
BUG: Extremely slow performance

### ISSUE THREAD

**Issue by shaneparsons** [beekeeper-studio/beekeeper-studio#752] opened 2021-08-03 14:52 UTC
**Describe the bug**
I just installed Beekeeper Studio for the first time now and in pulling up my first database connection (mysql) I immediately noticed a gigantic delay in resolving the table data. Even after it appears "loaded" resizing the window or scrolling freezes it up again. 

The database in question is fairly big, but some of the table's I'm opening only contain 6000 records or so, so it isn't the craziest. On competing products (sequel pro, table plus) this lag is completely non-existent. I'm not sure if it's because I'm running a slightly older version of macOS (Catalina / 10.15.7), or if it's because this app is built on electron where the others are native... But nothing else seems to have a problem with it. Any ideas?

**Expected behaviour**
The ability to actually browse / query the tables without a horrible lag every step of the way.

**Screenshots / Gifs**
This database has sensitive data, so I'd rather not take a screen cap if not needed. That being said, if a screen cap is the sole thing that can help you resolve this, let me know and I might be able to figure something out.

**Version Information (please complete the following information):**
 - OS: Mac mini (Late 2012) / 500GB SSD / 16GB Ram / macOS Catalina 10.15.7
 - App Version 1.13.2

**Additional context**
If there's any other information I can provide to help diagnose this I'd be more than happy to!

**Comment by dangelov** [comment] 2021-08-03 16:06
I'm using it on Windows and just noticed this today as well. It worked great till a few days ago, so I'm guessing it's something in the last update.

**Comment by SampsonCrowley** [comment] 2021-08-04 13:11
+1 there needs to be an option to limit rows without custom queries. The default paging offset is WAY too high for tables with large numbers of columns

**Comment by SampsonCrowley** [comment] 2021-08-04 13:13
Though now that I think about this, yes the performance used to be fine be fore latest update (osx, MacBook pro i9)

**Comment by SampsonCrowley** [comment] 2021-08-04 13:14
Should limit to 100 rows and paginate by default in my opinion. This is what pgadmin does and that is always speedy for me

**Comment by rathboma** [comment] 2021-08-09 14:58
@SampsonCrowley So sorry you're having some trouble here :-(. A few questions to help me get to the bottom of the issue:

1. What view locks up? Is it when you open a table in a tab, or when you run a query?
2. Table Tabs: How many columns are on the table? It might be the horizontal size making it slow
3. Table Tabs: Can you confirm that it does paginate to 100 rows at a time?
4. Query Tab: Does it happen when you select all 6000 rows?

Thanks so much for your help.

Matthew

**Comment by dangelov** [comment] 2021-08-11 12:44
Definitely a wide table issue. I have a table with about 70 columns and only showing 50 rows, the UI becomes near unusable. There is terrible lag everywhere even when just moving the mouse around (I can see hover states in sidebar changing every 2-3 seconds or so, so less than 1fps).

**Comment by SampsonCrowley** [comment] 2021-08-15 05:17
@rathboma it is the default table view. Simple double click to open.

It was happening on every table I was trying with, but I don't know column count of the top of my head;  somewhere ~ 20 on average per table. I can try to remember to get more accurate info next time I am at my laptop

I believe you are right about point #2, when I queried the same table in a custom query picking only the column I was looking for it was able to handle more than 100 rows

**Comment by shaneparsons** [comment] 2021-08-16 15:42
@rathboma yeah it definitely appears to be a "wide" table issue. I'm looking at a table right now with over 13m records, but because it only has 8 cols it seems to work great. On the opposite end, a table with only 155k records, and 49 cols is excruciatingly slow to navigate.

**Comment by johnjcamilleri** [comment] 2021-11-02 09:58
Same here. Someone above mentioned it worked well before, but I've tried all of the following versions and the problem exists in all, as far as I can tell.
- 2.1.4
- 1.13.2
- 1.12.0
- 1.11.3

**Comment by MattGson** [comment] 2021-11-14 20:40
Any ETA on this? Average table I'm working with has 10+ columns and is completely un-usable at the moment.

**Comment by rdelrossi** [comment] 2021-12-09 21:08
I'm glad I ran into this thread. Enjoy Beekeeper Studio a lot but hadn't put together the fact that the slowdowns are related to wide tables. With such tables, BKS 2.1.5 is really laggy.

**Comment by rathboma** [comment] 2021-12-10 15:20
Hey folks,

So sorry that this is still a problem. The good news is that Oli at Tabulator recently released a new version which includes a new framework for handling rendering.

Before the new release, it wasn't really possible for me to fix this in a maintainable way, but that's changed now!

It will still be a lot of work to improve horizontal render performance, but the framework is there. This is going to be my biggest priority in the new year. :muscle: 

Thanks for sticking with me through this!

**Comment by rdelrossi** [comment] 2021-12-15 19:27
> Thanks for sticking with me through this!

Thanks for a great prouduct! Frankly, now that I know the cause it's a lot easier to work around it.

**Comment by davidalexisnyt** [comment] 2021-12-17 16:56
The performance when dealing with large resultsets is deal-breaker for me.  The queries I do return millions of rows, which is not a problem with other tools like DBeaver, DataGrip, etc, because they automatically limit the number of rows returned and auto-fetch the next batch when you scroll past the end of the current batch. Reading the entire resultset into memory before rendering makes the UI unusable.

I love the look and feel of Beekeeper! It would be wonderful to be able to stop using clunky, Java-based query tools and switch to Beekeeper!

**Comment by sebnjk** [comment] 2021-12-20 06:45
> So sorry that this is still a problem.

I don't think there's anything be sorry about, it's not like you owe anything here :) Thanks for building and maintaining Beekeeper Studio!

**Comment by shadoWalker89** [comment] 2021-12-27 20:13
On windows (10) i'm connecting to a a mariadb and mysql locally on my machine.
I have a table with 5 rows, it takes 7 or 8 seconds to load the 5 rows, but when i do a select using a query tab the rows appear instantly

**Comment by rathboma** [comment] 2022-03-09 02:52
Hey everyone - I have a fix for performance problems with wide tables, can you all test the builds here:

https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/1955040800

and let me know if it helps things for you?

**Comment by otsaw** [comment] 2022-03-09 10:21
> https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/1955040800

Thanks, that works much better. The data scrolls fine now. There's still some issue with the column headers, they are lagging quite far behind the data when scrolling and sometimes when they finally move, they don't line up with the data.

**Comment by rathboma** [comment] 2022-03-09 13:34
Ok great news! Yes I've noticed that too but I'm having trouble replicating the issue outside of beekeeper studio.

Can I ask how many columns the table you were testing had? What behavior specifically made the headers go out of sync?

**Comment by otsaw** [comment] 2022-03-09 13:56
> Can I ask how many columns the table you were testing had? What behavior specifically made the headers go out of sync?

Tested with 79 columns. I can't really tell why the headers go out of sync, but it seems to happen in some tables, but not all, once I scroll far enough to the right. Also, it doesn't happen in the query results view, but does happen when opening the whole table in a tab, so maybe related to the key icons and types? (The query results view only has column names on the header.)

**Comment by rathboma** [comment] 2022-03-11 21:03
The column sync is fixed, and more improvements have been made, all thanks to Oli @ Tabulator, who is a legend.

I'm going to close this issue as the fix is merged and will be in the next release!

Tested with 1000 columns and still wicked fast.

**Closed by rathboma** 2022-03-11 21:03 UTC
