### ISSUE TITLE
BUG: Infinite loading. view table data

### ISSUE THREAD

**Issue by barrrettt** [beekeeper-studio/beekeeper-studio#1303] opened 2022-07-15 07:11 UTC
**Describe the bug**
Querries without results never end.  view table data.

**To Reproduce**
1. doble click on table with primarykey single column
2. enter a value that does not exist
3. click find
...

**Expected behavior**
0 results

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.
![image](https://user-images.githubusercontent.com/47840319/179169422-26b02fbc-6d55-4f82-af51-11365e0888b7.png)

**Version Information (please complete the following information):**
 - OS: win11
 - App Version 3.5.1
 - Database type mysql (latest or recent 2022/07, no remember now)

**Comment by niklas-stegmann** [comment] 2022-07-17 09:20
Duplicate of #1302

**Comment by azmy60** [comment] 2022-07-18 13:52
See #1289

**Closed** 2022-07-18 20:46 UTC
