### ISSUE TITLE
FEAT: data struct has no comment column

### ISSUE THREAD

**Issue by b0123456789** [beekeeper-studio/beekeeper-studio#1068] opened 2022-02-24 01:45 UTC
![image](https://user-images.githubusercontent.com/21169660/155441151-949712e1-d35c-487c-a329-5bbaf5a6eaef.png)

**Comment by rathboma** [comment] 2022-03-11 20:20
Yes agreed! Closing as a duplicate of #722, but it's on the TODO list.

**Closed by rathboma** 2022-03-11 20:20 UTC
