### ISSUE TITLE
Not everyone loves dark mode

### ISSUE THREAD

**Issue by lawless-m** [beekeeper-studio/beekeeper-studio#175] opened 2020-06-01 12:28 UTC
And I'm one of them. 

Any way to enable black-on-white ?

**Comment by ghstng** [comment] 2020-06-01 22:37
There is a light theme; we just haven't created a way to switch yet (Still working on a Settings View).

**Comment by tonyrein** [comment] 2020-06-04 19:49
Just adding my vote -- I never have understood the appeal of dark themes! Thank you for your work on this -- other than the theme it looks great, and I'm looking forward to being able to use it.
--T

**Comment by iKlsR** [comment] 2020-06-06 13:48
Duplicate of #26

**Comment by lawless-m** [comment] 2020-06-12 08:07
oh, sorry for the dupe, I did scan through but missed it

**Closed** 2020-06-12 08:08 UTC
Labels: ui/ux, working on it

**Comment by lawless-m** [comment] 2020-07-23 15:42
hey, you implemented it - thanks mate
