### ISSUE TITLE
FEAT: Editable tables even without a primary key 

### ISSUE THREAD

**Issue by ramiws** [beekeeper-studio/beekeeper-studio#1536] opened 2023-03-03 14:09 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot edit tables in beekeeper, while I can edit the same exact tables in other db software

**Describe the solution you'd like**
I want to the readonly icon to go away and I am able to edit the table 

**Additional context**
screenshot 
![Screenshot 2023-02-28 at 11 43 57](https://user-images.githubusercontent.com/31550346/222740931-0d761eeb-cd09-440f-b3d5-a24a527a164f.png)

**Database type, if appropriate**
In my case I am using  Postgresql. But I assume it is the same problem with any table without a primary key

**Comment by rathboma** [comment] 2023-03-03 18:06
Yep! We're doing this soon. See #1040 for SQLite, presumably this is similar in PSQL

**Comment by rathboma** [comment] 2023-03-03 18:07
Duplicate of #1532 - I'm going to close this issue, but we have this on the roadmap!

**Closed by rathboma** 2023-03-03 18:07 UTC

**Comment by davidkaufman** [comment] 2023-06-09 20:17
Yes #1522 will fix this for Postgres too, this is in progress and should be coming soon
