### ISSUE TITLE
Is there button or some kind shortcut to create new database

### ISSUE THREAD

**Issue by Bootta11** [beekeeper-studio/beekeeper-studio#935] opened 2021-12-28 07:30 UTC
**Details:**
It's strange that this kind tool no button to create new database. Maybe I'm missing it on GUI?

**Version Information [might be relevant to your issue]**
Operating System:  MacOS Montrey
App Version [help -> about]: 2.1.15

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment] 2022-01-17 02:42
Actually, no there isn't right now, sorry!

Duplicate of #840

**Closed by rathboma** 2022-01-17 02:42 UTC
