### ISSUE TITLE
BUG: Wrong Date Result when doing multiple conversions in a row

### ISSUE THREAD

**Issue by bab354** [beekeeper-studio/beekeeper-studio#511] opened 2021-01-10 17:40 UTC
**Describe the bug**
I notice that when doing date-time conversions in consecutive columns, BeeKeeper Studio is returning the wrong results (See Screenshot)

**To Reproduce**
Run this query inside BeeKeeper Studio
SELECT MAX(convert_timezone('gmt', 'est', '2020-10-01 00:48:04')),
       MAX('2020-10-01 00:48:04');

It returns the same result instead of converting only the top line
![image](https://user-images.githubusercontent.com/25424439/104130809-d87cc500-5340-11eb-82af-7460c9bb1713.png)

**Expected behavior**
the second result should not be converting (this is using DBeaver on Linux)
![image](https://user-images.githubusercontent.com/25424439/104130823-e3375a00-5340-11eb-9a93-3572591ec22f.png)

**Version Information (please complete the following information):**
OS: Ubuntu 18.04
App Version: 1.7.5

**Comment by UtechtDustin** [comment] 2021-01-11 08:29
Duplicate of #326

**Comment by rathboma** [comment] 2021-01-13 16:44
Yes, so sorry you're hitting this. It's a limitation of the PSQL client that I need to work around (it's a lot of work, so it's not done yet unfortunately).

If you give your columns an alias it works around it - `Select Max(..) as foo, max(...) as bar`

**Comment by rathboma** [comment] 2021-01-13 16:44
Going to close this as a dupe, but I really care about this issue and am prioritizing it soon

**Closed by rathboma** 2021-01-13 16:44 UTC
