### ISSUE TITLE
BUG:  "cd%" is being interpreted as a field name rather than search string

### ISSUE THREAD

**Issue by audiomuze** [beekeeper-studio/beekeeper-studio#795] opened 2021-09-14 06:59 UTC
**Describe the bug**
SQLite table structure for both tables being queried:
![image](https://user-images.githubusercontent.com/6852511/133209699-0c7386e4-64ee-43f0-a93c-d67d105ff53b.png)

```
SELECT
  b.__dirpath
FROM
  alibstats a
  INNER JOIN d5stats b ON (
    a.__dirname NOT LIKE "cd%"
    AND a.__dirname = b.__dirname
  )
  AND a.flac_count = b.flac_count
  AND a.dynamic_range = b.dynamic_range
  AND a.sampling_rate = b.sampling_rate
  AND a.bitspersample = b.bitspersample
ORDER BY
  b.__dirpath;
```

returns:  `no such column: cd%`

**To Reproduce**
create and run similar query

**Expected behavior**
Query should not throw an error. "cd%" is a criterion, not a field.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/6852511/133210229-14c42b43-77fe-42eb-80c2-c2c121c5f0dc.png)

**Version Information (please complete the following information):**
 - OS: Arch Linux
 - App Version: 2.0.0

**Comment by rathboma** [comment] 2021-09-14 19:43
So SQLite has a setting to interpret double quotes `"` as a string. I've disabled it by default and it is recommended to disable this with SQLite moving forwards.

To fix your issue change `"cd%"` to `'cd%'`.

Duplicate of #690

**Closed by rathboma** 2021-09-14 19:43 UTC
